name: Deploy Caddyfile to server

on:
  push

jobs:
  deploy-caddyfile:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Connect via SSH, pull repository and restart web server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull && sudo systemctl reload caddy && exit"
      - name: Clean up
        run: rm -rf ~/.ssh
